import gsap from "gsap";
import Head from "next/head";
import { useEffect } from "react";
import { Banner } from "../components/Banner/Banner";
import { MainForm } from "../components/MainForm";

export default function Home() {
  const tl = gsap.timeline({});

  useEffect(() => {
    tl.from(".texto", { translateX: "-50%", duration: 0.8 });
    tl.from(".avion", {
      duration: 1.2,
      translateX: "-300%",
      translateY: "10%",
      ease: "circ.out",
    });
    tl.from(".estrella", { opacity: 0, duration: 1 });
    tl.from(".mainform-overlay", { opacity: 0, translateX: -100 });
    tl.to("#logoytitulo", { opacity: 0 });
  }, []);

  return (
    <>
      <Head>
        <title>Aerospace - De punto a punto | Inicio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <MainForm />
    </>
  );
}
